export type {
  TrustBadge,
  ConversationStatus,
  RequestStatus,
  CatalogItemType,
  CatalogItem,
  Product,
  Profile,
  Order,
  OrderItem,
  OrderChannel,
  OrderStatus,
  Modality,
} from "./types";

import type {
  CatalogItem,
  ConversationStatus,
  RequestStatus,
  TrustBadge,
} from "./types";

export const categories = [
  "Gastronomía",
  "Moda e indumentaria",
  "Belleza y estética",
  "Hogar y deco",
  "Regalería",
  "Niños y bebés",
  "Eventos y celebraciones",
  "Servicios",
  "Oficios",
  "Arte y diseño",
  "Salud y bienestar",
  "Educación y talleres",
  "Mascotas",
  "Tecnología",
] as const;

export const categorySubcategories: Record<(typeof categories)[number], string[]> = {
  "Gastronomía": ["Pastelería", "Comida casera", "Panificados", "Catering"],
  "Moda e indumentaria": ["Indumentaria femenina", "Indumentaria infantil", "Accesorios", "Calzado"],
  "Belleza y estética": ["Maquillaje", "Peinado", "Uñas", "Cuidado de piel"],
  "Hogar y deco": ["Decoración", "Textil hogar", "Muebles", "Organización"],
  "Regalería": ["Florería", "Souvenirs", "Gift boxes", "Papelería"],
  "Niños y bebés": ["Indumentaria bebé", "Juguetes", "Estimulación", "Decoración infantil"],
  "Eventos y celebraciones": ["Candy bar", "Ambientación", "Fotografía", "Showrooms"],
  "Servicios": ["Asistencia virtual", "Community management", "Logística", "Impresión"],
  "Oficios": ["Carpintería", "Electricidad", "Plomería", "Herrería"],
  "Arte y diseño": ["Ilustración", "Diseño gráfico", "Cerámica", "Arte textil"],
  "Salud y bienestar": ["Masajes", "Nutrición", "Entrenamiento", "Terapias"],
  "Educación y talleres": ["Idiomas", "Apoyo escolar", "Manualidades", "Capacitaciones"],
  "Mascotas": ["Accesorios", "Alimento", "Peluquería", "Guardería"],
  "Tecnología": ["Soporte técnico", "Accesorios", "Reparación", "Automatización"],
};

export const entrepreneurs = [
  {
    id: "dulce-tentacion",
    name: "Dulce Tentación",
    category: "Gastronomía",
    subcategory: "Pastelería",
    rating: 4.8,
    reviews: 98,
    zone: "Quilmes",
    coverage: "Berazategui y zonas cercanas",
    cover: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?q=80&w=1200&auto=format&fit=crop",
    avatar: "https://images.unsplash.com/photo-1608198093002-ad4e005484ec?q=80&w=240&auto=format&fit=crop",
    badges: ["Verificado", "Responde rápido"] as TrustBadge[],
    about: "Pastelería artesanal para celebraciones, cafeterías y pedidos personalizados.",
    offers: ["Tortas temáticas", "Mini pastelería", "Mesas dulces"],
    responseTime: "Responde en menos de 1 hora",
    modality: "Retiro + envío programado",
    contactPhone: "5491112340001",
    modalities: ["retiro", "envío"],
    catalog: [
      {
        id: "dt-torta-animalitos",
        name: "Torta Animalitos 2 pisos",
        description: "Bizcochuelo de vainilla y relleno a elección.",
        image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?q=80&w=700&auto=format&fit=crop",
        price: 78000,
        type: "product",
        available: true,
        unit: "unidad",
        featured: true,
      },
      {
        id: "dt-box-cookies",
        name: "Box de cookies decoradas",
        description: "12 cookies personalizadas con temática a elección.",
        image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?q=80&w=700&auto=format&fit=crop",
        price: 18500,
        type: "product",
        available: true,
      },
      {
        id: "dt-catering-dulce",
        name: "Servicio de mesa dulce",
        description: "Armado y reposición durante 4 horas para eventos.",
        image: "https://images.unsplash.com/photo-1519676867240-f03562e64548?q=80&w=700&auto=format&fit=crop",
        type: "service",
        available: true,
      },
    ] as CatalogItem[],
  },
  {
    id: "luz-makeup",
    name: "Luz Makeup",
    category: "Belleza y estética",
    subcategory: "Maquillaje",
    rating: 4.7,
    reviews: 76,
    zone: "Hudson",
    coverage: "Berazategui, Hudson y Quilmes",
    cover: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?q=80&w=1200&auto=format&fit=crop",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=240&auto=format&fit=crop",
    badges: ["Responde rápido"] as TrustBadge[],
    about: "Maquillaje social y peinado para fiestas, sesiones y eventos corporativos.",
    offers: ["Maquillaje social", "Peinado", "Pack grupal"],
    responseTime: "Responde en el día",
    modality: "A domicilio y en estudio",
    contactPhone: "5491112340002",
    modalities: ["atención a domicilio", "online"],
    catalog: [
      {
        id: "lm-social",
        name: "Maquillaje social",
        description: "Look personalizado con productos HD.",
        image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=700&auto=format&fit=crop",
        price: 42000,
        type: "product",
        available: true,
        unit: "sesión",
        featured: true,
      },
      {
        id: "lm-pack-novia",
        name: "Pack novia civil",
        description: "Prueba previa + maquillaje + peinado.",
        image: "https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?q=80&w=700&auto=format&fit=crop",
        type: "service",
        available: true,
      },
      {
        id: "lm-clase",
        name: "Automaquillaje online",
        description: "Clase virtual de 90 minutos.",
        image: "https://images.unsplash.com/photo-1629196914168-95f4fddfdb93?q=80&w=700&auto=format&fit=crop",
        price: 18000,
        type: "product",
        available: true,
      },
    ] as CatalogItem[],
  },
  {
    id: "flores-mia",
    name: "Flores Mía",
    category: "Regalería",
    subcategory: "Florería",
    rating: 4.8,
    reviews: 64,
    zone: "Berazategui",
    coverage: "Berazategui y Florencio Varela",
    cover: "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?q=80&w=1200&auto=format&fit=crop",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=240&auto=format&fit=crop",
    badges: ["Top en tu zona"] as TrustBadge[],
    about: "Bouquets, arreglos y regalos florales con entrega programada.",
    offers: ["Ramos", "Centros de mesa", "Gift floral"],
    responseTime: "Responde en menos de 4 horas",
    modality: "Entrega y retiro",
    contactPhone: "5491112340003",
    modalities: ["retiro", "envío"],
    catalog: [
      {
        id: "fm-bouquet",
        name: "Bouquet premium",
        description: "Rosas, lisianthus y verdes de estación.",
        image: "https://images.unsplash.com/photo-1508610048659-a06b669e3321?q=80&w=700&auto=format&fit=crop",
        price: 29500,
        type: "product",
        available: true,
        featured: true,
      },
      {
        id: "fm-box-regalo",
        name: "Gift box floral",
        description: "Flores + tarjeta + bombones.",
        image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=700&auto=format&fit=crop",
        price: 36000,
        type: "product",
        available: true,
      },
      {
        id: "fm-corporativo",
        name: "Decoración floral corporativa",
        description: "Servicio mensual para oficinas y locales.",
        image: "https://images.unsplash.com/photo-1519378058457-4c29a0a2efac?q=80&w=700&auto=format&fit=crop",
        type: "service",
        available: true,
      },
    ] as CatalogItem[],
  },
  {
    id: "deco-alma",
    name: "Deco Alma",
    category: "Hogar y deco",
    subcategory: "Decoración",
    rating: 4.6,
    reviews: 52,
    zone: "Temperley",
    coverage: "Zona Sur",
    cover: "https://images.unsplash.com/photo-1478147427282-58a87a120781?q=80&w=1200&auto=format&fit=crop",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=240&auto=format&fit=crop",
    badges: ["Responde rápido", "Nuevo en Niar"] as TrustBadge[],
    about: "Piezas decorativas y asesoría para ambientar tu casa o local.",
    offers: ["Velas y aromas", "Textiles", "Asesoría"],
    responseTime: "Responde en el día",
    modality: "Online + showroom",
    contactPhone: "5491112340004",
    modalities: ["retiro", "envío", "online"],
    catalog: [
      { id: "da-vela", name: "Vela de soja XL", description: "Vela aromática reutilizable.", image: "https://images.unsplash.com/photo-1603006905003-be475563bc59?q=80&w=700&auto=format&fit=crop", price: 12000, type: "product", available: true },
      { id: "da-manta", name: "Manta tejida artesanal", description: "Manta de algodón 1,5x2m.", image: "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?q=80&w=700&auto=format&fit=crop", price: 24500, type: "product", available: true },
      { id: "da-asesoria", name: "Asesoría deco para living", description: "Propuesta visual + shopping list.", image: "https://images.unsplash.com/photo-1493666438817-866a91353ca9?q=80&w=700&auto=format&fit=crop", type: "service", available: true },
    ] as CatalogItem[],
  },
  {
    id: "manos-del-sur",
    name: "Manos del Sur",
    category: "Arte y diseño",
    subcategory: "Cerámica",
    rating: 4.9,
    reviews: 121,
    zone: "Berazategui",
    coverage: "Berazategui + envíos nacionales",
    cover: "https://images.unsplash.com/photo-1514996550219-62672472d03b?q=80&w=1200&auto=format&fit=crop",
    avatar: "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?q=80&w=240&auto=format&fit=crop",
    badges: ["Verificado", "Top en tu zona"] as TrustBadge[],
    about: "Piezas de cerámica utilitaria y objetos decorativos hechos a mano.",
    offers: ["Tazas", "Vajilla", "Piezas a medida"],
    responseTime: "Responde en menos de 2 horas",
    modality: "Showroom + envíos",
    contactPhone: "5491112340005",
    modalities: ["retiro", "envío", "online"],
    catalog: [
      { id: "ms-taza", name: "Taza esmaltada", description: "Taza de cerámica de 350ml.", image: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?q=80&w=700&auto=format&fit=crop", price: 14500, type: "product", available: true },
      { id: "ms-vajilla", name: "Set vajilla 4 piezas", description: "Plato playo + hondo + bowl + taza.", image: "https://images.unsplash.com/photo-1601058268499-e52658b8bb88?q=80&w=700&auto=format&fit=crop", price: 68000, type: "product", available: true, featured: true },
      { id: "ms-personalizado", name: "Pieza personalizada", description: "Diseño y modelado según pedido.", image: "https://images.unsplash.com/photo-1603199506016-b9aa4f85f4d5?q=80&w=700&auto=format&fit=crop", type: "service", available: true },
    ] as CatalogItem[],
  },
  {
    id: "huellitas-bera",
    name: "Huellitas Bera",
    category: "Mascotas",
    subcategory: "Accesorios",
    rating: 4.8,
    reviews: 88,
    zone: "Berazategui",
    coverage: "Berazategui y Quilmes",
    cover: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?q=80&w=1200&auto=format&fit=crop",
    avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=240&auto=format&fit=crop",
    badges: ["Verificado"] as TrustBadge[],
    about: "Accesorios, snacks y productos de bienestar para perros y gatos.",
    offers: ["Collares", "Snacks", "Kits de paseo"],
    responseTime: "Responde en menos de 2 horas",
    modality: "Retiro y envío",
    contactPhone: "5491112340006",
    modalities: ["retiro", "envío"],
    catalog: [
      { id: "hb-collar", name: "Collar ajustable premium", description: "Collar con broche reforzado.", image: "https://images.unsplash.com/photo-1517849845537-4d257902454a?q=80&w=700&auto=format&fit=crop", price: 9800, type: "product", available: true, featured: true },
      { id: "hb-snack", name: "Snack natural mix", description: "Bolsa de 500g sin conservantes.", image: "https://images.unsplash.com/photo-1589924691995-400dc9ecc119?q=80&w=700&auto=format&fit=crop", price: 7400, type: "product", available: true },
      { id: "hb-asesoria", name: "Asesoría nutricional canina", description: "Evaluación y plan básico.", image: "https://images.unsplash.com/photo-1548767797-d8c844163c4c?q=80&w=700&auto=format&fit=crop", type: "service", available: false },
    ] as CatalogItem[],
  },
  {
    id: "click-kids-fotografia",
    name: "Click Kids Fotografía",
    category: "Eventos y celebraciones",
    subcategory: "Fotografía",
    rating: 4.9,
    reviews: 151,
    zone: "Berazategui",
    coverage: "Zona Sur",
    cover: "https://images.unsplash.com/photo-1527631746610-bca00a040d60?q=80&w=1200&auto=format&fit=crop",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=240&auto=format&fit=crop",
    badges: ["Verificado", "Top en tu zona"] as TrustBadge[],
    about: "Fotografía espontánea para familias, eventos y marcas locales.",
    offers: ["Cobertura", "Mini books", "Edición"],
    responseTime: "Responde en menos de 1 hora",
    modality: "Cobertura presencial",
    contactPhone: "5491112340007",
    modalities: ["atención a domicilio"],
    catalog: [
      { id: "ck-book", name: "Mini book familiar", description: "Sesión de 1 hora + 20 fotos editadas.", image: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?q=80&w=700&auto=format&fit=crop", price: 58000, type: "product", available: true, unit: "sesión" },
      { id: "ck-evento", name: "Cobertura de evento", description: "Cobertura de 4 horas con entrega digital.", image: "https://images.unsplash.com/photo-1472653431158-6364773b2a56?q=80&w=700&auto=format&fit=crop", type: "service", available: true },
      { id: "ck-video", name: "Reel resumen", description: "Edición vertical para redes sociales.", image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?q=80&w=700&auto=format&fit=crop", price: 32000, type: "product", available: true },
    ] as CatalogItem[],
  },
  {
    id: "candy-house",
    name: "Candy House",
    category: "Eventos y celebraciones",
    subcategory: "Candy bar",
    rating: 4.7,
    reviews: 88,
    zone: "Lanús",
    coverage: "Lanús, Avellaneda y Berazategui",
    cover: "https://images.unsplash.com/photo-1481391032119-d89fee407e44?q=80&w=1200&auto=format&fit=crop",
    avatar: "https://images.unsplash.com/photo-1546961329-78bef0414d7c?q=80&w=240&auto=format&fit=crop",
    badges: ["Verificado"] as TrustBadge[],
    about: "Mesas dulces temáticas, souvenirs y ambientación para celebraciones.",
    offers: ["Candy bar", "Souvenirs", "Temáticas"],
    responseTime: "Responde en menos de 2 horas",
    modality: "Armado en salón",
    contactPhone: "5491112340008",
    modalities: ["atención a domicilio"],
    catalog: [
      { id: "ch-candy", name: "Candy bar 30 personas", description: "Mesa dulce completa con cartelería.", image: "https://images.unsplash.com/photo-1542826438-bd32f43d626f?q=80&w=700&auto=format&fit=crop", price: 89000, type: "product", available: true },
      { id: "ch-kit", name: "Kit cumple en casa", description: "Banderines, toppers y bolsitas temáticas.", image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?q=80&w=700&auto=format&fit=crop", price: 26500, type: "product", available: true },
      { id: "ch-diseno", name: "Diseño temático integral", description: "Propuesta personalizada según temática.", image: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?q=80&w=700&auto=format&fit=crop", type: "service", available: true },
    ] as CatalogItem[],
  },
  {
    id: "taller-urbano",
    name: "Taller Urbano",
    category: "Oficios",
    subcategory: "Carpintería",
    rating: 4.8,
    reviews: 73,
    zone: "Berazategui",
    coverage: "Berazategui y alrededores",
    cover: "https://images.unsplash.com/photo-1541976076758-347942db1978?q=80&w=1200&auto=format&fit=crop",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=240&auto=format&fit=crop",
    badges: ["Verificado", "Responde rápido"] as TrustBadge[],
    about: "Muebles a medida, restauración y soluciones para hogares y locales.",
    offers: ["Muebles a medida", "Restauración", "Asesoría"],
    responseTime: "Responde en menos de 3 horas",
    modality: "Visita a domicilio + taller",
    contactPhone: "5491112340009",
    modalities: ["atención a domicilio", "retiro"],
    catalog: [
      { id: "tu-estante", name: "Estante flotante", description: "Madera paraíso, 80cm.", image: "https://images.unsplash.com/photo-1616627454190-8b1f7185f08f?q=80&w=700&auto=format&fit=crop", price: 52000, type: "product", available: true },
      { id: "tu-mueble", name: "Mueble a medida", description: "Diseño y fabricación personalizada.", image: "https://images.unsplash.com/photo-1523413651479-597eb2da0ad6?q=80&w=700&auto=format&fit=crop", type: "service", available: true },
      { id: "tu-restauracion", name: "Restauración de muebles", description: "Recuperación estética y funcional.", image: "https://images.unsplash.com/photo-1574873215043-7be019ad0ea3?q=80&w=700&auto=format&fit=crop", type: "service", available: true },
    ] as CatalogItem[],
  },
  {
    id: "mini-mundo-bebe",
    name: "Mini Mundo Bebé",
    category: "Niños y bebés",
    subcategory: "Indumentaria bebé",
    rating: 4.9,
    reviews: 109,
    zone: "Avellaneda",
    coverage: "Zona Sur + envíos a CABA",
    cover: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?q=80&w=1200&auto=format&fit=crop",
    avatar: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?q=80&w=240&auto=format&fit=crop",
    badges: ["Verificado", "Top en tu zona", "Recomendado"] as TrustBadge[],
    about: "Ropa, accesorios y kits de primera infancia para regalar o uso diario.",
    offers: ["Ajuar", "Juguetes", "Regalos"],
    responseTime: "Responde en menos de 1 hora",
    modality: "Showroom + envíos",
    contactPhone: "5491112340010",
    modalities: ["retiro", "envío"],
    catalog: [
      { id: "mm-ajuar", name: "Ajuar recién nacido", description: "5 prendas de algodón premium.", image: "https://images.unsplash.com/photo-1519689680058-324335c77eba?q=80&w=700&auto=format&fit=crop", price: 42000, type: "product", available: true },
      { id: "mm-manta", name: "Manta plush", description: "Manta hipoalergénica de 90x90.", image: "https://images.unsplash.com/photo-1536640712-4d4c36ff0e4e?q=80&w=700&auto=format&fit=crop", price: 16500, type: "product", available: true },
      { id: "mm-regalo", name: "Gift card personalizada", description: "Arma tu caja regalo según presupuesto.", image: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?q=80&w=700&auto=format&fit=crop", type: "service", available: true },
    ] as CatalogItem[],
  },
] as const;

export const popularProducts = entrepreneurs.flatMap((entrepreneur) =>
  entrepreneur.catalog
    .filter((item) => item.type === "product" && item.price)
    .slice(0, 2)
    .map((item) => ({ ...item, entrepreneurId: entrepreneur.id, entrepreneurName: entrepreneur.name })),
);

export const events = [
  {
    id: "feria-emprendedores-hudson",
    name: "Feria Emprendedores Hudson",
    date: "Sábado 18 de mayo",
    location: "Plaza de Hudson",
    category: "Eventos y celebraciones",
    image: "https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=1200&auto=format&fit=crop",
    entrepreneursCount: 42,
    description: "Una feria al aire libre con propuestas de deco, gastronomía, diseño y servicios locales.",
    participantIds: ["manos-del-sur", "click-kids-fotografia", "candy-house"],
  },
  {
    id: "showroom-creativo-berazategui",
    name: "Showroom Creativo Berazategui",
    date: "Domingo 26 de mayo",
    location: "Centro Cultural Berazategui",
    category: "Arte y diseño",
    image: "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?q=80&w=1200&auto=format&fit=crop",
    entrepreneursCount: 27,
    description: "Showroom con productos de diseño, regalos, moda y hogar hechos por emprendedores locales.",
    participantIds: ["deco-alma", "flores-mia", "mini-mundo-bebe"],
  },
  {
    id: "ronda-negocios-zona-sur",
    name: "Ronda de Negocios Zona Sur",
    date: "Sábado 15 de junio",
    location: "Polo Gastronómico Lanús",
    category: "Servicios",
    image: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?q=80&w=1200&auto=format&fit=crop",
    entrepreneursCount: 54,
    description: "Espacio de networking para conectar emprendedores, comercios y potenciales clientes.",
    participantIds: ["luz-makeup", "taller-urbano", "dulce-tentacion"],
  },
];

export const requests = [
  {
    id: "req-torta-personalizada",
    title: "Necesito una torta personalizada",
    category: "Gastronomía",
    date: "12 de mayo",
    zone: "Berazategui",
    budget: "$85.000",
    description: "Busco torta temática para 30 personas con entrega el mismo día.",
    proposals: 6,
    status: "En evaluación" as RequestStatus,
  },
  {
    id: "req-regalo-artesanal",
    title: "Busco regalo artesanal",
    category: "Regalería",
    date: "25 de mayo",
    zone: "Hudson",
    budget: "$45.000",
    description: "Quiero una gift box con flores y piezas de cerámica para un aniversario.",
    proposals: 4,
    status: "Recibiendo propuestas" as RequestStatus,
  },
  {
    id: "req-maquillaje-fiesta",
    title: "Necesito maquillaje para una fiesta",
    category: "Belleza y estética",
    date: "8 de junio",
    zone: "Quilmes",
    budget: "A definir",
    description: "Maquillaje social para 2 personas con opción de peinado.",
    proposals: 3,
    status: "Recibiendo propuestas" as RequestStatus,
  },
  {
    id: "req-mueble-medida",
    title: "Busco quien haga muebles a medida",
    category: "Oficios",
    date: "15 de junio",
    zone: "Avellaneda",
    budget: "$220.000",
    description: "Mueble de guardado para living con diseño moderno y medidas personalizadas.",
    proposals: 2,
    status: "Cerrada" as RequestStatus,
  },
  {
    id: "req-productos-mascota",
    title: "Necesito productos para mi mascota",
    category: "Mascotas",
    date: "20 de junio",
    zone: "Berazategui",
    budget: "$30.000",
    description: "Collar, snack y kit de paseo para perro mediano.",
    proposals: 5,
    status: "En evaluación" as RequestStatus,
  },
];

export const conversations = [
  {
    id: "conv-1",
    entrepreneurId: "dulce-tentacion",
    requestId: "req-torta-personalizada",
    lastMessage: "Te envié dos opciones de sabor y diseño para la torta.",
    status: "Presupuesto enviado" as ConversationStatus,
    summary: "Torta personalizada • 30 personas",
    timestamp: "10:24",
  },
  {
    id: "conv-2",
    entrepreneurId: "manos-del-sur",
    requestId: "req-regalo-artesanal",
    lastMessage: "Podemos combinar set de cerámica + bouquet, ¿querés que te lo cotice?",
    status: "En conversación" as ConversationStatus,
    summary: "Gift artesanal • aniversario",
    timestamp: "Ayer",
  },
  {
    id: "conv-3",
    entrepreneurId: "luz-makeup",
    requestId: "req-maquillaje-fiesta",
    lastMessage: "Si te parece, te paso propuesta con peinado incluido.",
    status: "Esperando respuesta" as ConversationStatus,
    summary: "Makeup para fiesta",
    timestamp: "Lun",
  },
  {
    id: "conv-4",
    entrepreneurId: "taller-urbano",
    requestId: "req-mueble-medida",
    lastMessage: "¡Gracias por elegirnos! Confirmamos visita de medición.",
    status: "Propuesta aceptada" as ConversationStatus,
    summary: "Mueble a medida",
    timestamp: "Dom",
  },
];

export const chatMessages = [
  { id: "m1", sender: "user", text: "Hola, vi tu perfil y quiero una torta temática para 30 personas.", at: "09:14" },
  { id: "m2", sender: "entrepreneur", text: "¡Hola! Genial, ¿tenés fecha y temática en mente?", at: "09:17" },
  { id: "m3", sender: "user", text: "Sí, 12 de mayo y temática animalitos.", at: "09:18" },
  { id: "m4", sender: "entrepreneur", text: "Perfecto, te envié una propuesta estructurada abajo 👇", at: "09:22" },
] as const;

export const proposal = {
  estimatedPrice: "$82.000",
  availability: "Disponible para el 12 de mayo",
  includes: [
    "Torta temática de 2 pisos",
    "Topper personalizado",
    "Entrega en Berazategui",
  ],
  references: [
    "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?q=80&w=700&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1578985545062-69928b1d9587?q=80&w=700&auto=format&fit=crop",
  ],
};

export const requestComparisons = {
  "req-torta-personalizada": [
    {
      entrepreneurId: "dulce-tentacion",
      price: "$82.000",
      includes: "Torta temática + topper + entrega.",
      eta: "Disponible para el 12 de mayo",
      status: "Presupuesto enviado" as ConversationStatus,
    },
    {
      entrepreneurId: "candy-house",
      price: "$89.000",
      includes: "Torta + mini candy bar temático.",
      eta: "Disponible con 72 hs de anticipación",
      status: "En conversación" as ConversationStatus,
    },
  ],
  "req-regalo-artesanal": [
    {
      entrepreneurId: "manos-del-sur",
      price: "$44.000",
      includes: "Set cerámica artesanal + empaque regalo.",
      eta: "Listo en 3 días",
      status: "En conversación" as ConversationStatus,
    },
    {
      entrepreneurId: "flores-mia",
      price: "$39.000",
      includes: "Gift floral + tarjeta personalizada.",
      eta: "Entrega en 24 hs",
      status: "Presupuesto enviado" as ConversationStatus,
    },
  ],
  "req-maquillaje-fiesta": [
    {
      entrepreneurId: "luz-makeup",
      price: "$78.000",
      includes: "Maquillaje para 2 personas + retoques.",
      eta: "Disponible el día del evento",
      status: "Esperando respuesta" as ConversationStatus,
    },
  ],
  "req-mueble-medida": [
    {
      entrepreneurId: "taller-urbano",
      price: "$220.000",
      includes: "Diseño + fabricación + instalación.",
      eta: "Entrega estimada en 20 días",
      status: "Propuesta aceptada" as ConversationStatus,
    },
  ],
  "req-productos-mascota": [
    {
      entrepreneurId: "huellitas-bera",
      price: "$28.000",
      includes: "Collar + snacks + kit de paseo.",
      eta: "Retiro inmediato",
      status: "Presupuesto enviado" as ConversationStatus,
    },
  ],
} as const;

export const getEntrepreneurById = (id: string) =>
  entrepreneurs.find((e) => e.id === id);

export const getRequestById = (id: string) => requests.find((r) => r.id === id);
