export type TrustBadge = "Verificado" | "Responde rápido" | "Top en tu zona";
export type ConversationStatus =
  | "Presupuesto enviado"
  | "En conversación"
  | "Esperando respuesta"
  | "Propuesta aceptada";
export type RequestStatus = "Recibiendo propuestas" | "En evaluación" | "Cerrada";

export const categories = [
  "Cumpleaños",
  "Eventos",
  "Decoración",
  "Tortas y dulces",
  "Candy bar",
  "Fotografía",
  "Belleza",
  "Indumentaria",
  "Regalería",
  "Hogar",
  "Mascotas",
  "Servicios",
] as const;

export const entrepreneurs = [
  {
    id: "decorarte-eventos",
    name: "DecorArte Eventos",
    category: "Decoración",
    rating: 4.9,
    reviews: 124,
    zone: "Berazategui",
    cover: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?q=80&w=1200&auto=format&fit=crop",
    avatar: "https://images.unsplash.com/photo-1567581935884-3349723552ca?q=80&w=240&auto=format&fit=crop",
    badges: ["Verificado", "Top en tu zona"] as TrustBadge[],
    about: "Creamos ambientaciones cálidas para cumpleaños, baby showers y eventos familiares.",
    offers: ["Fondos para torta", "Backdrops personalizados", "Candy bar integral"],
    responseTime: "Responde en menos de 2 horas",
    modality: "A domicilio + armado en salón",
  },
  {
    id: "dulce-tentacion",
    name: "Dulce Tentación",
    category: "Tortas y dulces",
    rating: 4.8,
    reviews: 98,
    zone: "Quilmes",
    cover: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?q=80&w=1200&auto=format&fit=crop",
    avatar: "https://images.unsplash.com/photo-1608198093002-ad4e005484ec?q=80&w=240&auto=format&fit=crop",
    badges: ["Verificado", "Responde rápido"] as TrustBadge[],
    about: "Tortas temáticas y mesas dulces para celebraciones memorables.",
    offers: ["Torta personalizada", "Mini pastelería", "Servicio de entrega"],
    responseTime: "Responde en menos de 1 hora",
    modality: "Retiro + envío programado",
  },
  {
    id: "luz-makeup",
    name: "Luz Makeup",
    category: "Belleza",
    rating: 4.7,
    reviews: 76,
    zone: "Hudson",
    cover: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?q=80&w=1200&auto=format&fit=crop",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=240&auto=format&fit=crop",
    badges: ["Responde rápido"] as TrustBadge[],
    about: "Makeup social y peinado para eventos, sesiones y fiestas.",
    offers: ["Maquillaje social", "Peinado express", "Pack madre e hija"],
    responseTime: "Responde en el día",
    modality: "En estudio o a domicilio",
  },
  {
    id: "flores-mia",
    name: "Flores Mía",
    category: "Decoración",
    rating: 4.8,
    reviews: 64,
    zone: "Berazategui",
    cover: "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?q=80&w=1200&auto=format&fit=crop",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=240&auto=format&fit=crop",
    badges: ["Top en tu zona"] as TrustBadge[],
    about: "Arreglos florales y ambientación botánica para eventos.",
    offers: ["Centros de mesa", "Arcos florales", "Bouquets personalizados"],
    responseTime: "Responde en menos de 4 horas",
    modality: "Entrega + montaje",
  },
  {
    id: "pequenos-momentos",
    name: "Pequeños Momentos",
    category: "Eventos",
    rating: 4.9,
    reviews: 182,
    zone: "Avellaneda",
    cover: "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?q=80&w=1200&auto=format&fit=crop",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=240&auto=format&fit=crop",
    badges: ["Verificado", "Top en tu zona", "Responde rápido"] as TrustBadge[],
    about: "Organización integral de eventos infantiles y familiares.",
    offers: ["Planificación", "Proveedores", "Coordinación en sitio"],
    responseTime: "Responde en menos de 30 minutos",
    modality: "Servicio integral",
  },
  {
    id: "candy-house",
    name: "Candy House",
    category: "Candy bar",
    rating: 4.7,
    reviews: 88,
    zone: "Lanús",
    cover: "https://images.unsplash.com/photo-1481391032119-d89fee407e44?q=80&w=1200&auto=format&fit=crop",
    avatar: "https://images.unsplash.com/photo-1546961329-78bef0414d7c?q=80&w=240&auto=format&fit=crop",
    badges: ["Verificado"] as TrustBadge[],
    about: "Mesas dulces temáticas con diseño personalizado.",
    offers: ["Candy bar completo", "Temáticas infantiles", "Souvenirs dulces"],
    responseTime: "Responde en menos de 2 horas",
    modality: "Armado en salón",
  },
  {
    id: "click-kids-fotografia",
    name: "Click Kids Fotografía",
    category: "Fotografía",
    rating: 4.9,
    reviews: 151,
    zone: "Berazategui",
    cover: "https://images.unsplash.com/photo-1527631746610-bca00a040d60?q=80&w=1200&auto=format&fit=crop",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=240&auto=format&fit=crop",
    badges: ["Verificado", "Top en tu zona"] as TrustBadge[],
    about: "Fotografía espontánea de eventos, cumpleaños y books infantiles.",
    offers: ["Cobertura completa", "Mini books", "Entrega digital"],
    responseTime: "Responde en menos de 1 hora",
    modality: "Cobertura presencial",
  },
  {
    id: "deco-alma",
    name: "Deco Alma",
    category: "Decoración",
    rating: 4.6,
    reviews: 52,
    zone: "Temperley",
    cover: "https://images.unsplash.com/photo-1478147427282-58a87a120781?q=80&w=1200&auto=format&fit=crop",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=240&auto=format&fit=crop",
    badges: ["Responde rápido"] as TrustBadge[],
    about: "Decoración boutique para eventos íntimos y celebraciones especiales.",
    offers: ["Ambientación minimal", "Papelería creativa", "Asesoría visual"],
    responseTime: "Responde en el día",
    modality: "Diseño + montaje",
  },
];

export const events = [
  {
    id: "feria-emprendedores-hudson",
    name: "Feria Emprendedores Hudson",
    date: "Sábado 18 de mayo",
    location: "Plaza de Hudson",
    category: "Eventos",
    image: "https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=1200&auto=format&fit=crop",
    entrepreneursCount: 42,
    description: "Una feria al aire libre con propuestas de decoración, dulces, fotografía y más.",
    participantIds: ["decorarte-eventos", "click-kids-fotografia", "candy-house"],
  },
  {
    id: "showroom-creativo-berazategui",
    name: "Showroom Creativo Berazategui",
    date: "Domingo 26 de mayo",
    location: "Centro Cultural Berazategui",
    category: "Decoración",
    image: "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?q=80&w=1200&auto=format&fit=crop",
    entrepreneursCount: 27,
    description: "Showroom con emprendedores creativos de zona sur y experiencias en vivo.",
    participantIds: ["deco-alma", "flores-mia", "dulce-tentacion"],
  },
  {
    id: "feria-deco-kids",
    name: "Feria Deco & Kids",
    date: "Sábado 1 de junio",
    location: "Club Social Quilmes",
    category: "Cumpleaños",
    image: "https://images.unsplash.com/photo-1464207687429-7505649dae38?q=80&w=1200&auto=format&fit=crop",
    entrepreneursCount: 35,
    description: "Todo para cumpleaños infantiles, animación y ambientación temática.",
    participantIds: ["pequenos-momentos", "decorarte-eventos", "candy-house"],
  },
  {
    id: "encuentro-emprendedor-zona-sur",
    name: "Encuentro Emprendedor Zona Sur",
    date: "Sábado 15 de junio",
    location: "Polo Gastronómico Lanús",
    category: "Servicios",
    image: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?q=80&w=1200&auto=format&fit=crop",
    entrepreneursCount: 54,
    description: "Encuentro de networking y exposición para contratar emprendedores locales.",
    participantIds: ["luz-makeup", "click-kids-fotografia", "deco-alma"],
  },
];

export const requests = [
  {
    id: "req-cumple-1",
    title: "Cumpleaños infantil 1 año",
    category: "Cumpleaños",
    date: "12 de mayo",
    zone: "Berazategui",
    budget: "$180.000",
    description:
      "Necesito decoración para fondo de torta, candy bar y ambientación simple para 25 personas.",
    proposals: 6,
    status: "En evaluación" as RequestStatus,
  },
  {
    id: "req-baby-shower",
    title: "Ambientación baby shower",
    category: "Decoración",
    date: "25 de mayo",
    zone: "Hudson",
    budget: "$120.000",
    description: "Busco ambientación delicada con tonos pastel y sector de fotos.",
    proposals: 4,
    status: "Recibiendo propuestas" as RequestStatus,
  },
  {
    id: "req-torta",
    title: "Torta personalizada",
    category: "Tortas y dulces",
    date: "8 de junio",
    zone: "Quilmes",
    budget: "A definir",
    description: "Torta temática de animales para 30 personas.",
    proposals: 3,
    status: "Recibiendo propuestas" as RequestStatus,
  },
  {
    id: "req-foto-familiar",
    title: "Fotografía para evento familiar",
    category: "Fotografía",
    date: "15 de junio",
    zone: "Avellaneda",
    budget: "$95.000",
    description: "Cobertura de 4 horas con entrega digital.",
    proposals: 2,
    status: "Cerrada" as RequestStatus,
  },
];

export const conversations = [
  {
    id: "conv-1",
    entrepreneurId: "decorarte-eventos",
    requestId: "req-cumple-1",
    lastMessage: "Te envié una propuesta con dos opciones de ambientación.",
    status: "Presupuesto enviado" as ConversationStatus,
    summary: "Cumpleaños 1 año • Candy bar + decoración",
    timestamp: "10:24",
  },
  {
    id: "conv-2",
    entrepreneurId: "click-kids-fotografia",
    requestId: "req-foto-familiar",
    lastMessage: "¡Gracias! Si querés, reservo la fecha hoy.",
    status: "Propuesta aceptada" as ConversationStatus,
    summary: "Cobertura familiar • 4 horas",
    timestamp: "Ayer",
  },
  {
    id: "conv-3",
    entrepreneurId: "candy-house",
    requestId: "req-cumple-1",
    lastMessage: "¿Te gustaría incluir mesa salada también?",
    status: "En conversación" as ConversationStatus,
    summary: "Cumpleaños 1 año • Mesa dulce",
    timestamp: "Lun",
  },
  {
    id: "conv-4",
    entrepreneurId: "luz-makeup",
    requestId: "req-baby-shower",
    lastMessage: "Quedo atenta a tu feedback para ajustar la propuesta.",
    status: "Esperando respuesta" as ConversationStatus,
    summary: "Baby shower • Makeup social",
    timestamp: "Dom",
  },
];

export const chatMessages = [
  { id: "m1", sender: "user", text: "Hola, me interesa una propuesta para el cumple de mi bebé.", at: "09:14" },
  { id: "m2", sender: "entrepreneur", text: "¡Hola! Gracias por escribirme. ¿La fecha sigue siendo 12 de mayo?", at: "09:17" },
  { id: "m3", sender: "user", text: "Sí, en Berazategui. Quiero algo simple pero lindo.", at: "09:18" },
  { id: "m4", sender: "entrepreneur", text: "Perfecto, te envié una propuesta estructurada abajo 👇", at: "09:22" },
] as const;

export const proposal = {
  estimatedPrice: "$165.000",
  availability: "Disponible para el 12 de mayo",
  includes: [
    "Fondo de torta temático de 2,5m",
    "Candy bar para 25 personas",
    "Armado y desarmado en 4 horas",
  ],
  references: [
    "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?q=80&w=700&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?q=80&w=700&auto=format&fit=crop",
  ],
};

export const getEntrepreneurById = (id: string) =>
  entrepreneurs.find((e) => e.id === id);

export const getRequestById = (id: string) => requests.find((r) => r.id === id);
